### PR TITLE
Add arrays, defined with the characters "[]" after a key name

### PR DESCRIPTION
**Pull request by StevenSchoch**
Several suggestions have been made on the web to add arrays to INI files.
This branch has implemented the method of adding square brackets after the key name.

### CODE REVIEW

**Comment by ronsavage** [comment]
Hi Steven

Looks good, but let me just cogitate for a while...

---
Cheers
Ron
savage.net.au

**Comment by StevenSchoch** [comment]
Thank you, Ron!

**Review by ronsavage — APPROVED** [review]
Looks ok. Merging...

**Comment by ronsavage** [comment]
I tests perfectly on my Debian box.
Well done!

**Comment by ronsavage** [comment]
Oops. I should be It

**Comment by ronsavage** [comment]
I will update the POD and push to MetaCPAN.

**Comment by ronsavage** [comment]
I have uploaded V 2.30 to CPAN.
Plz see the Changes file for details.
Alternately, see https://metacpan.org/dist/Config-Tiny
Thanx!

**Comment by StevenSchoch** [comment]
Ron, thank you for including my my small addition to your library!

**Comment by ronsavage** [comment]
I've posted a little article about our work to https://blogs.perl.org/

**Comment by ronsavage** [comment]
Can now update version # from command line.
Started numbering of sections.
Try with:
perl scripts/preprocess.pl
perl scripts/preprocess.pl -v 2.01

**Pull request merged**
